[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "example_one.py"
name = "Example One"
icon = ":books:"

[[pages]]
path = "example_four.py"
name = "Example Four"
icon = "ğŸ“–"

[[pages]]
path = "example_two.py"
name = "Example Two"
icon = "âœï¸"

[[pages]]
path = "example_three.py"

[[pages]]
path = "example_five.py"
name = "Example Five"
icon = "ğŸ§°"